version: '3'

services: 
     server:
          build:
               context: .
          ports: 
               - '5000:5000'
          volumes: 
               - .:/code
          command: >
               sh -c 'python runserver.py'
