version: "3"

services: 
     server:
          build:
               context: .
          ports: 
               - "5000:5000"
          volumes: 
               - .:/code
          command: >
               export FLASK_APP=runserver.py
               sh -c "python runserver.py"
